apiVersion: v1
kind : Secret
metadata: 
  name: postgres-secret
data:
  # credenciales encodeadas en base64 de user , postgres y appdb
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cG9zdGdyZXM= 
  POSTGRES_DB: YXBwZGI= 